# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          df -h
          
#       - name: Commit files
#         run: |
#          git config --local user.email "16505692+tangger2000@users.noreply.github.com"
#          git config --local user.name "github-actions[bot]"
#          git clone https://github.com/tangger2000/laion-face.git
#          cd laion-face
#         wget -l1 -r --no-parent https://the-eye.eu/public/AI/cah/laion400m-met-release/laion400m-meta/
#          mv the-eye.eu/public/AI/cah/laion400m-met-release/laion400m-meta/ .
#          wget https://huggingface.co/datasets/FacePerceiver/laion-face/resolve/main/laion_face_ids.pth
#          wget https://raw.githubusercontent.com/FacePerceiver/LAION-Face/master/convert_parquet.py
#          python convert_parquet.py ./laion_face_ids.pth ./laion400m-meta ./laion_face_meta
#          git commit -a -m "Add changes"
          
#       - name: Push changes
#         uses: ad-m/github-push-action@master
#         with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
